### PR TITLE
GitHub Actions to compile and upload artifacts

### PR DESCRIPTION
**Pull request by ThreeDeeJay**
GitHub actions to compile Cavern.sln and upload binaries as a zip file. 
It doesn't compile the full Unity app because that's a lot more complicated than just compiling the DLLs, but they might be helpful to test updates as soon as they're pushed.
I was finally able to play an Atmos file by manually replacing the DLLs from 1.5, although the audio was a bit choppy. I just literally could not wait for the official release 😄 
It can be downloaded from the Artifacts section of the latest workflow run like this one https://github.com/ThreeDeeJay/Cavern/actions/runs/3248273096

### CODE REVIEW

**Comment by VoidXH** [comment]
Thank you, really nice! Is there a way to also put Cavern.Format (which contains Atmos support) in the zip?

**Comment by ThreeDeeJay** [comment]
It should be doable. 
So lemme see if I got it right, should the folder structure of the new files look like this?:
- cavern64
	- Cavern_Data
		- Managed
			- Cavern.dll
			- Cavern.QuickEQ.dll
			- Cavern.Format.dll
	- Plugins
		- x86_64
			- CavernAmp.dll
and are there any other solutions/project files needed to be compiled?
Also, should I do anything with the XMLs and JSON files that got compiled in [Cavern.zip](https://github.com/ThreeDeeJay/Cavern/suites/8772379533/artifacts/398009586) or just ignore them?

**Comment by VoidXH** [comment]
Everything's correct, only these 4 files are needed for driver updates.

**Comment by ThreeDeeJay** [comment]
huh, guess I should've merged before pushing commits to avoid that failed check.
but anyway, it's done:
- Now it uses the same folder structure as the current Cavern driver (1.5) so we can just drag and drop/overwrite to update it
- Latest binaries are now added to GitHub (pre-)releases in addition to the expiring artifact in the workflow run. 
So the latest DLLs should always be available via https://github.com/ThreeDeeJay/Cavern/releases/tag/latest

**Comment by ThreeDeeJay** [comment]
Oh wait, there's a small mistake with one of the DLL paths. Fixing now..

**Comment by ThreeDeeJay** [comment]
Fixed.

**Comment by VoidXH** [comment]
Perfect, thank you!

**Comment by ThreeDeeJay** [comment]
Awesome!
Just a heads up, the github actions file is hardcoded to load some files from the [netstandard2.1](https://github.com/VoidXH/Cavern/actions/runs/3256099566/jobs/5346119125#step:8:3) folder, so if that ever changes or the build just fails due to a different path change, [Build.yml](https://github.com/VoidXH/Cavern/blob/f36ad1d529be393940ce690f9892f8f536b07ad9/.github/workflows/Build.yml#L43) will need to be updated.

**Pull request merged**
